export const userLoginConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
}

export const userRegisterConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
}

export const userUpdateConstants = {
    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_FAILURE: 'UPDATE_FAILURE',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
}

export const getUserConstants = {
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_FAILURE: 'GET_USER_FAILURE',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
}

export const otpConstants = {
    OTP_REQUEST: 'OTP_REQUEST',
    OTP_FAILURE: 'OTP_FAILURE',
    OTP_SUCCESS: 'OTP_SUCCESS',
}

export const contactEmailConstants = {
    CONTACT_EMAIL_REQUEST: 'CONTACT_EMAIL_REQUEST',
    CONTACT_EMAIL_FAILURE: 'CONTACT_EMAIL_FAILURE',
    CONTACT_EMAIL_SUCCESS: 'CONTACT_EMAIL_SUCCESS',
}

export const emailConstants = {
    EMAIL_REQUEST: 'EMAIL_REQUEST',
    EMAIL_FAILURE: 'EMAIL_FAILURE',
    EMAIL_SUCCESS: 'EMAIL_SUCCESS',
}

export const productConstants = {
    PRODUCT_REQUEST: 'PRODUCT_REQUEST',
    PRODUCT_FAILURE: 'PRODUCT_FAILURE',
    PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
}

export const newProductConstants = {
    NEW_PRODUCT_REQUEST: 'NEW_PRODUCT_REQUEST',
    NEW_PRODUCT_FAILURE: 'NEW_PRODUCT_FAILURE',
    NEW_PRODUCT_SUCCESS: 'NEW_PRODUCT_SUCCESS',
}

export const singleProductConstants = {
    SINGLE_PRODUCT_REQUEST: 'SINGLE_PRODUCT_REQUEST',
    SINGLE_PRODUCT_FAILURE: 'SINGLE_PRODUCT_FAILURE',
    SINGLE_PRODUCT_SUCCESS: 'SINGLE_PRODUCT_SUCCESS',
}

export const categoryConstants = {
    CATEGORY_REQUEST: 'CATEGORY_REQUEST',
    CATEGORY_FAILURE: 'CATEGORY_FAILURE',
    CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',
}

export const searchConstants = {
    SEARCH_REQUEST: 'SEARCH_REQUEST',
    SEARCH_FAILURE: 'SEARCH_FAILURE',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
}

export const filterConstants = {
    FILTER_REQUEST: 'FILTER_REQUEST',
    FILTER_FAILURE: 'FILTER_FAILURE',
    FILTER_SUCCESS: 'FILTER_SUCCESS',
}

export const relatedConstants = {
    RELATED_REQUEST: 'RELATED_REQUEST',
    RELATED_FAILURE: 'RELATED_FAILURE',
    RELATED_SUCCESS: 'RELATED_SUCCESS',
}

export const addToCartConstants = {
    ADDTOCART_REQUEST: 'ADDTOCART_REQUEST',
    ADDTOCART_FAILURE: 'ADDTOCART_FAILURE',
    ADDTOCART_SUCCESS: 'ADDTOCART_SUCCESS',
}

export const getCartDataConstants = {
    GETCARTDATA_REQUEST: 'GETCARTDATA_REQUEST',
    GETCARTDATA_FAILURE: 'GETCARTDATA_FAILURE',
    GETCARTDATA_SUCCESS: 'GETCARTDATA_SUCCESS',
}
export const removeCartDataConstants = {
    REMOVECARTDATA_REQUEST: 'REMOVECARTDATA_REQUEST',
    REMOVECARTDATA_FAILURE: 'REMOVECARTDATA_FAILURE',
    REMOVECARTDATA_SUCCESS: 'REMOVECARTDATA_SUCCESS',
}

export const removeSavedDataConstants = {
    REMOVE_SAVED_REQUEST: 'REMOVE_SAVED_REQUEST',
    REMOVE_SAVED_FAILURE: 'REMOVE_SAVED_FAILURE',
    REMOVE_SAVED_SUCCESS: 'REMOVE_SAVED_SUCCESS',
}

export const quantityEditConstants = {
    QUANTITY_EDIT_REQUEST: 'QUANTITY_EDIT_REQUEST',
    QUANTITY_EDIT_FAILURE: 'QUANTITY_EDIT_FAILURE',
    QUANTITY_EDIT_SUCCESS: 'QUANTITY_EDIT_SUCCESS',
}

export const orderConstants = {
    ORDER_REQUEST: 'ORDER_REQUEST',
    ORDER_FAILURE: 'ORDER_FAILURE',
    ORDER_SUCCESS: 'ORDER_SUCCESS',
}

export const orderPersonalizeConstants = {
    ORDER_PERSONALIZED_REQUEST: 'ORDER_PERSONALIZED_REQUEST',
    ORDER_PERSONALIZED_FAILURE: 'ORDER_PERSONALIZED_FAILURE',
    ORDER_PERSONALIZED_SUCCESS: 'ORDER_PERSONALIZED_SUCCESS',
}


export const paymentVerifyConstants = {
    PAYMENT_VERIFY_REQUEST: 'PAYMENT_VERIFY_REQUEST',
    PAYMENT_VERIFY_FAILURE: 'PAYMENT_VERIFY_FAILURE',
    PAYMENT_VERIFY_SUCCESS: 'PAYMENT_VERIFY_SUCCESS',
}

export const paymentConstants = {
    PAYMENT_REQUEST: 'PAYMENT_REQUEST',
    PAYMENT_FAILURE: 'PAYMENT_FAILURE',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
}

export const trendingProductsConstants = {
    TRENDING_PRODUCTS_REQUEST: 'TRENDING_PRODUCTS_REQUEST',
    TRENDING_PRODUCTS_FAILURE: 'TRENDING_PRODUCTS_FAILURE',
    TRENDING_PRODUCTS_SUCCESS: 'TRENDING_PRODUCTS_SUCCESS',
}

export const saveConstants = {
    SAVE_REQUEST: 'SAVE_REQUEST',
    SAVE_FAILURE: 'SAVE_FAILURE',
    SAVE_SUCCESS: 'SAVE_SUCCESS',
}

export const getSavedConstants = {
    GET_SAVED_REQUEST: 'GET_SAVED_REQUEST',
    GET_SAVED_FAILURE: 'GET_SAVED_FAILURE',
    GET_SAVED_SUCCESS: 'GET_SAVED_SUCCESS',
}
export const getUserOrdersConstant = {
    USER_ORDERS_REQUEST: 'USER_ORDERS_REQUEST',
    USER_ORDERS_FAILURE: 'USER_ORDERS_FAILURE',
    USER_ORDERS_SUCCESS: 'USER_ORDERS_SUCCESS',
}
export const setPageConstant = {
    PAGE_REQUEST: 'PAGE_REQUEST',
    PAGE_FAILURE: 'PAGE_FAILURE',
    PAGE_SUCCESS: 'PAGE_SUCCESS',
}

export const initialCartDataConstant = {
    INITIAL_CART_DATA_REQUEST: 'INITIAL_CART_DATA_REQUEST',
    INITIAL_CART_DATA_FAILURE: 'INITIAL_CART_DATA_FAILURE',
    INITIAL_CART_DATA_SUCCESS: 'INITIAL_CART_DATA_SUCCESS',
}

export const googleLoginConstant = {
    GOOGLE_LOGIN_REQUEST: 'GOOGLE_LOGIN_REQUEST',
    GOOGLE_LOGIN_FAILURE: 'GOOGLE_LOGIN_FAILURE',
    GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
}


export const allCategoryConstants = {
    ALL_CATEGORY_REQUEST: 'ALL_CATEGORY_REQUEST',
    ALL_CATEGORY_SUCCESS: 'ALL_CATEGORY_SUCCESS',
    ALL_CATEGORY_FAILURE: 'ALL_CATEGORY_FAILURE',
}

export const checkCouponConstants = {
    CHECK_COUPON_REQUEST: 'CHECK_COUPON_REQUEST',
    CHECK_COUPON_SUCCESS: 'CHECK_COUPON_SUCCESS',
    CHECK_COUPON_FAILURE: 'CHECK_COUPON_FAILURE',
}

export const getGiftBoxConstants = {
    GET_GIFTBOX_REQUEST: 'GET_GIFTBOX_REQUEST',
    GET_GIFTBOX_SUCCESS: 'GET_GIFTBOX_SUCCESS',
    GET_GIFTBOX_FAILURE: 'GET_GIFTBOX_FAILURE',
}

export const getGiftCardConstants = {
    GET_GIFTCARD_REQUEST: 'GET_GIFTCARD_REQUEST',
    GET_GIFTCARD_SUCCESS: 'GET_GIFTCARD_SUCCESS',
    GET_GIFTCARD_FAILURE: 'GET_GIFTCARD_FAILURE',
}

export const getNotificationConstants = {
    GET_NOTIFICATIONS_REQUEST: 'GET_NOTIFICATIONS_REQUEST',
    GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
    GET_NOTIFICATIONS_FAILURE: 'GET_NOTIFICATIONS_FAILURE',
}